import Head from 'next/head';
import { Parallax, ParallaxLayer } from '@react-spring/parallax';

import ComputerInception3D from '../components/computerInception3';
import Typing from '../components/typing';


export default function Home() {
  return (
    <>
      <Head>
        <title>JacKJack</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Parallax pages={4}>
        
        <ParallaxLayer
          offset={0}
          speed={1}
          // factor={2}
          // style={{
          //   backgroundImage: `url(${moon})`,
          //   backgroundSize: 'cover',
          // }}
        > 
          <div style={{display: 'flex', flexDirection: 'column', height: '100vh', alignItems: 'center', justifyContent: 'center'}}>
            <Typing text={["Wbu wyd?"]} cssName={'name'} />
            <Typing text={["Zaza keeps running over my keyboatfdysgu2718uy32h"]} cssName={'subtitle'} />
          </div>
        </ParallaxLayer>
        <ParallaxLayer
          sticky={{start: 0, end: 2.5}}
        >
          <img src='/assets/cat.gif' />
        </ParallaxLayer>
        <ParallaxLayer
          offset={1}
          speed={0.5}
        >
          <div style={{display: 'flex', flexDirection: 'column', height: '100vh', alignItems: 'center', justifyContent: 'center'}}>
            <Typing text={["Wbu wyd?"]} cssName={'name'} />
            <Typing text={["Zaza keeps running over my keyboatfdysgu2718uy32h"]} cssName={'subtitle'} />
          </div>
        </ParallaxLayer>
      </Parallax>
      
    </>
  );
}